---
apiVersion: v1
kind: Pod
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  containers:
  - name: httpbin-container
    image: kennethreitz/httpbin
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"

